# Generated by Django 5.0.14 on 2026-09-16 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0013_correctionproposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='floor',
            field=models.CharField(blank=True, help_text="Floor or level, if indoors, e.g. '3rd floor'", max_length=50),
        ),
        migrations.AddField(
            model_name='camera',
            name='nearby_room',
            field=models.CharField(blank=True, help_text='Nearby room, unit, or landmark, if known', max_length=255),
        ),
        migrations.AddField(
            model_name='camera',
            name='reporter_notes',
            field=models.TextField(blank=True, help_text='Additional notes submitted by the reporter'),
        ),
    ]
