# Generated by Django 5.0.14 on 2026-09-16 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0014_camera_floor_camera_nearby_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='building',
            field=models.CharField(blank=True, help_text="Building name or number, if known, e.g. 'Building 32 (Stata Center)'", max_length=255),
        ),
    ]
