# Generated by Django 5.0.14 on 2026-09-16 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0015_camera_building'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='camera_type',
        ),
    ]
