# Generated by Django 5.0.14 on 2026-09-17 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0018_backfill_camera_short_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='short_code',
            field=models.CharField(blank=True, editable=False, help_text="Short auto-generated camera ID, e.g. '0483'", max_length=4, unique=True),
        ),
    ]
