# Generated by Django 5.0.14 on 2026-09-17 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0019_alter_camera_short_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameraimage',
            name='photo_type',
            field=models.CharField(choices=[('surrounding', 'Surrounding'), ('close_up', 'Close Up')], default='close_up', max_length=30),
        ),
    ]
