# Generated by Django 5.0.14 on 2026-09-17 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0020_alter_cameraimage_photo_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='short_code',
        ),
    ]
