# Generated by Django 5.0.14 on 2026-09-23 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0021_remove_camera_short_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='placement',
            field=models.CharField(blank=True, choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor')], db_index=True, help_text='Is the camera indoors or outdoors?', max_length=10),
        ),
    ]
