# Generated by Django 5.0.14 on 2026-09-23 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0022_camera_placement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='cross_road',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='osm_id',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='reported_by',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='street_address',
        ),
    ]
