# Generated by Django 5.0.14 on 2026-09-23 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0023_remove_camera_cross_road_remove_camera_direction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='associated_shop',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='facial_recognition',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='notes',
        ),
    ]
